name: Schedule Content Release

on:
  schedule:
    # Schedule to run at your desired UTC time and date
    # Example: '00 10 7 3 *' would run at 10:00 AM, March 7th UTC.
    - cron: 'MINUTE HOUR DAY MONTH *'

jobs:
  release-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: scheduled-content  # Make sure this matches your branch name

      - name: Merge scheduled content into main
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git fetch origin main
          git checkout main
          git merge --no-ff scheduled-content -m "Merge scheduled content into main"
          git push origin main
